//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPO_WPF_Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("système")]
        public string SystemUsername {
            get {
                return ((string)(this["SystemUsername"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La variable info n\'est pas correcte")]
        public string CycleInfo_Error01 {
            get {
                return ((string)(this["CycleInfo_Error01"]));
            }
            set {
                this["CycleInfo_Error01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La commande envoyé n\'a rien renvoyé")]
        public string CycleInfo_Error02 {
            get {
                return ((string)(this["CycleInfo_Error02"]));
            }
            set {
                this["CycleInfo_Error02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CycleInfo_checkAlarmsTimer_Interval {
            get {
                return ((int)(this["CycleInfo_checkAlarmsTimer_Interval"]));
            }
            set {
                this["CycleInfo_checkAlarmsTimer_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classe utilisée incorrecte")]
        public string CycleInfo_Error03 {
            get {
                return ((string)(this["CycleInfo_Error03"]));
            }
            set {
                this["CycleInfo_Error03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Statut")]
        public string CycleInfo_Mix_StatusField {
            get {
                return ((string)(this["CycleInfo_Mix_StatusField"]));
            }
            set {
                this["CycleInfo_Mix_StatusField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("En attente")]
        public string CycleInfo_Mix_StatusWaiting {
            get {
                return ((string)(this["CycleInfo_Mix_StatusWaiting"]));
            }
            set {
                this["CycleInfo_Mix_StatusWaiting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("En cours")]
        public string CycleInfo_Mix_StatusOnGoing {
            get {
                return ((string)(this["CycleInfo_Mix_StatusOnGoing"]));
            }
            set {
                this["CycleInfo_Mix_StatusOnGoing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terminé")]
        public string CycleInfo_Mix_StatusEnded {
            get {
                return ((string)(this["CycleInfo_Mix_StatusEnded"]));
            }
            set {
                this["CycleInfo_Mix_StatusEnded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int CycleMix_timeSeqController {
            get {
                return ((int)(this["CycleMix_timeSeqController"]));
            }
            set {
                this["CycleMix_timeSeqController"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CycleMix_timeCheckAlarms_Interval {
            get {
                return ((int)(this["CycleMix_timeCheckAlarms_Interval"]));
            }
            set {
                this["CycleMix_timeCheckAlarms_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int CycleMix_timeoutPumpNotFree {
            get {
                return ((int)(this["CycleMix_timeoutPumpNotFree"]));
            }
            set {
                this["CycleMix_timeoutPumpNotFree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int CycleMix_timeoutTempTooHotDuringCycle {
            get {
                return ((int)(this["CycleMix_timeoutTempTooHotDuringCycle"]));
            }
            set {
                this["CycleMix_timeoutTempTooHotDuringCycle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int CycleMix_timeoutTempTooHotBeforeCycle {
            get {
                return ((int)(this["CycleMix_timeoutTempTooHotBeforeCycle"]));
            }
            set {
                this["CycleMix_timeoutTempTooHotBeforeCycle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int CycleMix_timeoutSequenceTooLong {
            get {
                return ((int)(this["CycleMix_timeoutSequenceTooLong"]));
            }
            set {
                this["CycleMix_timeoutSequenceTooLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int CycleMix_timeoutSequenceBlocked {
            get {
                return ((int)(this["CycleMix_timeoutSequenceBlocked"]));
            }
            set {
                this["CycleMix_timeoutSequenceBlocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CycleMix_sequenceTimer_Interval {
            get {
                return ((int)(this["CycleMix_sequenceTimer_Interval"]));
            }
            set {
                this["CycleMix_sequenceTimer_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CycleMix_pumpNotFreeTimer_Interval {
            get {
                return ((int)(this["CycleMix_pumpNotFreeTimer_Interval"]));
            }
            set {
                this["CycleMix_pumpNotFreeTimer_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CycleMix_tempControlTimer_Interval {
            get {
                return ((int)(this["CycleMix_tempControlTimer_Interval"]));
            }
            set {
                this["CycleMix_tempControlTimer_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipeSpeedMixerInfo est null")]
        public string CycleMix_Erro01 {
            get {
                return ((string)(this["CycleMix_Erro01"]));
            }
            set {
                this["CycleMix_Erro01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Veuillez fermer le capot avant de démarrer le cycle")]
        public string CycleMix_Request_CloseLid {
            get {
                return ((string)(this["CycleMix_Request_CloseLid"]));
            }
            set {
                this["CycleMix_Request_CloseLid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cliquez sur OK pour démarrer le speedmixer")]
        public string CycleMix_Request_StartMix {
            get {
                return ((string)(this["CycleMix_Request_StartMix"]));
            }
            set {
                this["CycleMix_Request_StartMix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Température du piège froid trop chaude")]
        public string CycleMix_Error_TempTooHot {
            get {
                return ((string)(this["CycleMix_Error_TempTooHot"]));
            }
            set {
                this["CycleMix_Error_TempTooHot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Problème avec le speedmixer, fin de cycle")]
        public string CycleMix_Error_MixTooLong {
            get {
                return ((string)(this["CycleMix_Error_MixTooLong"]));
            }
            set {
                this["CycleMix_Error_MixTooLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le speedmixer ne répond plus, cycle avorté")]
        public string CycleMix_Error_MixerBlocked {
            get {
                return ((string)(this["CycleMix_Error_MixerBlocked"]));
            }
            set {
                this["CycleMix_Error_MixerBlocked"] = value;
            }
        }
    }
}
