//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarm_Management.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alarme")]
        public string AlarmType_Alarm {
            get {
                return ((string)(this["AlarmType_Alarm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alerte")]
        public string AlarmType_Warning {
            get {
                return ((string)(this["AlarmType_Warning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aucun")]
        public string AlarmType_None {
            get {
                return ((string)(this["AlarmType_None"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La classe n\'est pas initialisée")]
        public string Error01 {
            get {
                return ((string)(this["Error01"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L\'alarme est déjà active")]
        public string Error02 {
            get {
                return ((string)(this["Error02"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L\'alarme est inactive mais ne fait pas parti des alarmes actives")]
        public string Error03 {
            get {
                return ((string)(this["Error03"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L\'alarme ne fait pas parti des alarmes actives")]
        public string Error04 {
            get {
                return ((string)(this["Error04"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L\'alarme est déjà inactive")]
        public string Error05 {
            get {
                return ((string)(this["Error05"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Statut de l\'alarme avant inactivation ou aquittement incorrect")]
        public string Error06 {
            get {
                return ((string)(this["Error06"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type d\'alarme incorrect")]
        public string Error07 {
            get {
                return ((string)(this["Error07"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ConfigAlarms xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <configAlarms>
    <ConfigAlarm>
      <id1>0</id1>
      <id2>0</id2>
      <description>Connexion à la balance échouée</description>
      <type>Alarm</type>
    </ConfigAlarm>
    <ConfigAlarm>
      <id1>1</id1>
      <id2>0</id2>
      <description>Connexion au SpeedMixer échouée</description>
      <type>Alarm</type>
    </ConfigAlarm>
    <ConfigAlarm>
      <id1>1</id1>
      <id2>1</id2>
      <description>Erreur du speedmixer pendant un cycle</description>
      <type>Alarm</type>
    </ConfigAlarm>
    <ConfigAlarm>
      <id1>2</id1>
      <id2>0</id2>
      <description>Connexion à la pompe à vide échouée</description>
      <type>Alarm</type>
    </ConfigAlarm>
    <ConfigAlarm>
      <id1>3</id1>
      <id2>0</id2>
      <description>Connexion au piège froid échouée</description>
      <type>Alarm</type>
    </ConfigAlarm>
    <ConfigAlarm>
      <id1>3</id1>
      <id2>1</id2>
      <description>Température trop haute pendant le cycle</description>
      <type>Alarm</type>
    </ConfigAlarm>
    <ConfigAlarm>
      <id1>4</id1>
      <id2>0</id2>
      <description>Backup automatique complet de la base de données échoué aprés 3 tentatives</description>
      <type>Warning</type>
    </ConfigAlarm>
  </configAlarms>
</ConfigAlarms>")]
        public global::Alarm_Management.ConfigAlarms Alarms {
            get {
                return ((global::Alarm_Management.ConfigAlarms)(this["Alarms"]));
            }
        }
    }
}
