### YamlMime:ManagedReference
items:
- uid: Database.DatabaseSettings
  commentId: T:Database.DatabaseSettings
  id: DatabaseSettings
  parent: Database
  children:
  - Database.DatabaseSettings.ConnectionInfo
  - Database.DatabaseSettings.DBAppFolder
  - Database.DatabaseSettings.Error_connectToDbFailed
  - Database.DatabaseSettings.General_FalseValue_Read
  - Database.DatabaseSettings.General_FalseValue_Write
  - Database.DatabaseSettings.General_TrueValue_Read
  - Database.DatabaseSettings.General_TrueValue_Write
  - Database.DatabaseSettings.Timestamp_Format
  langs:
  - csharp
  - vb
  name: DatabaseSettings
  nameWithType: DatabaseSettings
  fullName: Database.DatabaseSettings
  type: Class
  source:
    id: DatabaseSettings
    path: C:\Temp\MixingApplication\Database\MyDatabase.cs
    startLine: 82
  assemblies:
  - Database
  namespace: Database
  summary: "\nStatic class used to allow other projects to access some values from the settings\n"
  example: []
  syntax:
    content: public static class DatabaseSettings
    content.vb: Public Module DatabaseSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Database.DatabaseSettings.Error_connectToDbFailed
  commentId: P:Database.DatabaseSettings.Error_connectToDbFailed
  id: Error_connectToDbFailed
  parent: Database.DatabaseSettings
  langs:
  - csharp
  - vb
  name: Error_connectToDbFailed
  nameWithType: DatabaseSettings.Error_connectToDbFailed
  fullName: Database.DatabaseSettings.Error_connectToDbFailed
  type: Property
  source:
    id: Error_connectToDbFailed
    path: C:\Temp\MixingApplication\Database\MyDatabase.cs
    startLine: 85
  assemblies:
  - Database
  namespace: Database
  example: []
  syntax:
    content: public static string Error_connectToDbFailed { get; }
    parameters: []
    return:
      type: System.String
      description: Message displayed if the connection to the database fails
    content.vb: Public Shared ReadOnly Property Error_connectToDbFailed As String
  overload: Database.DatabaseSettings.Error_connectToDbFailed*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Database.DatabaseSettings.General_TrueValue_Read
  commentId: P:Database.DatabaseSettings.General_TrueValue_Read
  id: General_TrueValue_Read
  parent: Database.DatabaseSettings
  langs:
  - csharp
  - vb
  name: General_TrueValue_Read
  nameWithType: DatabaseSettings.General_TrueValue_Read
  fullName: Database.DatabaseSettings.General_TrueValue_Read
  type: Property
  source:
    id: General_TrueValue_Read
    path: C:\Temp\MixingApplication\Database\MyDatabase.cs
    startLine: 87
  assemblies:
  - Database
  namespace: Database
  example: []
  syntax:
    content: public static string General_TrueValue_Read { get; }
    parameters: []
    return:
      type: System.String
      description: Value &quot;true&quot; when read from a database table
    content.vb: Public Shared ReadOnly Property General_TrueValue_Read As String
  overload: Database.DatabaseSettings.General_TrueValue_Read*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Database.DatabaseSettings.General_FalseValue_Read
  commentId: P:Database.DatabaseSettings.General_FalseValue_Read
  id: General_FalseValue_Read
  parent: Database.DatabaseSettings
  langs:
  - csharp
  - vb
  name: General_FalseValue_Read
  nameWithType: DatabaseSettings.General_FalseValue_Read
  fullName: Database.DatabaseSettings.General_FalseValue_Read
  type: Property
  source:
    id: General_FalseValue_Read
    path: C:\Temp\MixingApplication\Database\MyDatabase.cs
    startLine: 89
  assemblies:
  - Database
  namespace: Database
  example: []
  syntax:
    content: public static string General_FalseValue_Read { get; }
    parameters: []
    return:
      type: System.String
      description: Value &quot;false&quot; when read from a database table
    content.vb: Public Shared ReadOnly Property General_FalseValue_Read As String
  overload: Database.DatabaseSettings.General_FalseValue_Read*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Database.DatabaseSettings.General_TrueValue_Write
  commentId: P:Database.DatabaseSettings.General_TrueValue_Write
  id: General_TrueValue_Write
  parent: Database.DatabaseSettings
  langs:
  - csharp
  - vb
  name: General_TrueValue_Write
  nameWithType: DatabaseSettings.General_TrueValue_Write
  fullName: Database.DatabaseSettings.General_TrueValue_Write
  type: Property
  source:
    id: General_TrueValue_Write
    path: C:\Temp\MixingApplication\Database\MyDatabase.cs
    startLine: 91
  assemblies:
  - Database
  namespace: Database
  example: []
  syntax:
    content: public static string General_TrueValue_Write { get; }
    parameters: []
    return:
      type: System.String
      description: Value &quot;true&quot; to write to a database table
    content.vb: Public Shared ReadOnly Property General_TrueValue_Write As String
  overload: Database.DatabaseSettings.General_TrueValue_Write*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Database.DatabaseSettings.General_FalseValue_Write
  commentId: P:Database.DatabaseSettings.General_FalseValue_Write
  id: General_FalseValue_Write
  parent: Database.DatabaseSettings
  langs:
  - csharp
  - vb
  name: General_FalseValue_Write
  nameWithType: DatabaseSettings.General_FalseValue_Write
  fullName: Database.DatabaseSettings.General_FalseValue_Write
  type: Property
  source:
    id: General_FalseValue_Write
    path: C:\Temp\MixingApplication\Database\MyDatabase.cs
    startLine: 93
  assemblies:
  - Database
  namespace: Database
  example: []
  syntax:
    content: public static string General_FalseValue_Write { get; }
    parameters: []
    return:
      type: System.String
      description: Value &quot;false&quot; to write to a database table
    content.vb: Public Shared ReadOnly Property General_FalseValue_Write As String
  overload: Database.DatabaseSettings.General_FalseValue_Write*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Database.DatabaseSettings.ConnectionInfo
  commentId: P:Database.DatabaseSettings.ConnectionInfo
  id: ConnectionInfo
  parent: Database.DatabaseSettings
  langs:
  - csharp
  - vb
  name: ConnectionInfo
  nameWithType: DatabaseSettings.ConnectionInfo
  fullName: Database.DatabaseSettings.ConnectionInfo
  type: Property
  source:
    id: ConnectionInfo
    path: C:\Temp\MixingApplication\Database\MyDatabase.cs
    startLine: 95
  assemblies:
  - Database
  namespace: Database
  example: []
  syntax:
    content: public static ConnectionInfo ConnectionInfo { get; }
    parameters: []
    return:
      type: Database.ConnectionInfo
      description: Information of connection to the database
    content.vb: Public Shared ReadOnly Property ConnectionInfo As ConnectionInfo
  overload: Database.DatabaseSettings.ConnectionInfo*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Database.DatabaseSettings.DBAppFolder
  commentId: P:Database.DatabaseSettings.DBAppFolder
  id: DBAppFolder
  parent: Database.DatabaseSettings
  langs:
  - csharp
  - vb
  name: DBAppFolder
  nameWithType: DatabaseSettings.DBAppFolder
  fullName: Database.DatabaseSettings.DBAppFolder
  type: Property
  source:
    id: DBAppFolder
    path: C:\Temp\MixingApplication\Database\MyDatabase.cs
    startLine: 97
  assemblies:
  - Database
  namespace: Database
  example: []
  syntax:
    content: public static string DBAppFolder { get; }
    parameters: []
    return:
      type: System.String
      description: Folder of the application of the database
    content.vb: Public Shared ReadOnly Property DBAppFolder As String
  overload: Database.DatabaseSettings.DBAppFolder*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Database.DatabaseSettings.Timestamp_Format
  commentId: P:Database.DatabaseSettings.Timestamp_Format
  id: Timestamp_Format
  parent: Database.DatabaseSettings
  langs:
  - csharp
  - vb
  name: Timestamp_Format
  nameWithType: DatabaseSettings.Timestamp_Format
  fullName: Database.DatabaseSettings.Timestamp_Format
  type: Property
  source:
    id: Timestamp_Format
    path: C:\Temp\MixingApplication\Database\MyDatabase.cs
    startLine: 99
  assemblies:
  - Database
  namespace: Database
  example: []
  syntax:
    content: public static string Timestamp_Format { get; }
    parameters: []
    return:
      type: System.String
      description: Format of timestamps
    content.vb: Public Shared ReadOnly Property Timestamp_Format As String
  overload: Database.DatabaseSettings.Timestamp_Format*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Database
  commentId: N:Database
  name: Database
  nameWithType: Database
  fullName: Database
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Database.DatabaseSettings.Error_connectToDbFailed*
  commentId: Overload:Database.DatabaseSettings.Error_connectToDbFailed
  name: Error_connectToDbFailed
  nameWithType: DatabaseSettings.Error_connectToDbFailed
  fullName: Database.DatabaseSettings.Error_connectToDbFailed
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Database.DatabaseSettings.General_TrueValue_Read*
  commentId: Overload:Database.DatabaseSettings.General_TrueValue_Read
  name: General_TrueValue_Read
  nameWithType: DatabaseSettings.General_TrueValue_Read
  fullName: Database.DatabaseSettings.General_TrueValue_Read
- uid: Database.DatabaseSettings.General_FalseValue_Read*
  commentId: Overload:Database.DatabaseSettings.General_FalseValue_Read
  name: General_FalseValue_Read
  nameWithType: DatabaseSettings.General_FalseValue_Read
  fullName: Database.DatabaseSettings.General_FalseValue_Read
- uid: Database.DatabaseSettings.General_TrueValue_Write*
  commentId: Overload:Database.DatabaseSettings.General_TrueValue_Write
  name: General_TrueValue_Write
  nameWithType: DatabaseSettings.General_TrueValue_Write
  fullName: Database.DatabaseSettings.General_TrueValue_Write
- uid: Database.DatabaseSettings.General_FalseValue_Write*
  commentId: Overload:Database.DatabaseSettings.General_FalseValue_Write
  name: General_FalseValue_Write
  nameWithType: DatabaseSettings.General_FalseValue_Write
  fullName: Database.DatabaseSettings.General_FalseValue_Write
- uid: Database.DatabaseSettings.ConnectionInfo*
  commentId: Overload:Database.DatabaseSettings.ConnectionInfo
  name: ConnectionInfo
  nameWithType: DatabaseSettings.ConnectionInfo
  fullName: Database.DatabaseSettings.ConnectionInfo
- uid: Database.ConnectionInfo
  commentId: T:Database.ConnectionInfo
  parent: Database
  name: ConnectionInfo
  nameWithType: ConnectionInfo
  fullName: Database.ConnectionInfo
- uid: Database.DatabaseSettings.DBAppFolder*
  commentId: Overload:Database.DatabaseSettings.DBAppFolder
  name: DBAppFolder
  nameWithType: DatabaseSettings.DBAppFolder
  fullName: Database.DatabaseSettings.DBAppFolder
- uid: Database.DatabaseSettings.Timestamp_Format*
  commentId: Overload:Database.DatabaseSettings.Timestamp_Format
  name: Timestamp_Format
  nameWithType: DatabaseSettings.Timestamp_Format
  fullName: Database.DatabaseSettings.Timestamp_Format
