### YamlMime:ManagedReference
items:
- uid: Database
  commentId: N:Database
  id: Database
  children:
  - Database.AccessTableInfo
  - Database.AuditTrailInfo
  - Database.Column
  - Database.ConnectionInfo
  - Database.CycleSpeedMixerInfo
  - Database.CycleTableInfo
  - Database.CycleWeightInfo
  - Database.DailyTestInfo
  - Database.DatabaseSettings
  - Database.IBasTabInfo
  - Database.IComTabInfo
  - Database.ICycleSeqInfo
  - Database.IDtTabInfo
  - Database.IniInfo
  - Database.ISeqTabInfo
  - Database.MyDatabase
  - Database.ReadInfo
  - Database.RecipeInfo
  - Database.RecipeSpeedMixerInfo
  - Database.RecipeStatus
  - Database.RecipeWeightInfo
  - Database.TempInfo
  - Database.TempResultInfo
  langs:
  - csharp
  - vb
  name: Database
  nameWithType: Database
  fullName: Database
  type: Namespace
  assemblies:
  - Database
references:
- uid: Database.ConnectionInfo
  commentId: T:Database.ConnectionInfo
  parent: Database
  name: ConnectionInfo
  nameWithType: ConnectionInfo
  fullName: Database.ConnectionInfo
- uid: Database.IniInfo
  commentId: T:Database.IniInfo
  parent: Database
  name: IniInfo
  nameWithType: IniInfo
  fullName: Database.IniInfo
- uid: Database.RecipeStatus
  commentId: T:Database.RecipeStatus
  parent: Database
  name: RecipeStatus
  nameWithType: RecipeStatus
  fullName: Database.RecipeStatus
- uid: Database.DatabaseSettings
  commentId: T:Database.DatabaseSettings
  name: DatabaseSettings
  nameWithType: DatabaseSettings
  fullName: Database.DatabaseSettings
- uid: Database.ReadInfo
  commentId: T:Database.ReadInfo
  parent: Database
  name: ReadInfo
  nameWithType: ReadInfo
  fullName: Database.ReadInfo
- uid: Database.MyDatabase
  commentId: T:Database.MyDatabase
  name: MyDatabase
  nameWithType: MyDatabase
  fullName: Database.MyDatabase
- uid: Database.Column
  commentId: T:Database.Column
  name: Column
  nameWithType: Column
  fullName: Database.Column
- uid: Database.IBasTabInfo
  commentId: T:Database.IBasTabInfo
  parent: Database
  name: IBasTabInfo
  nameWithType: IBasTabInfo
  fullName: Database.IBasTabInfo
- uid: Database.IComTabInfo
  commentId: T:Database.IComTabInfo
  parent: Database
  name: IComTabInfo
  nameWithType: IComTabInfo
  fullName: Database.IComTabInfo
- uid: Database.IDtTabInfo
  commentId: T:Database.IDtTabInfo
  parent: Database
  name: IDtTabInfo
  nameWithType: IDtTabInfo
  fullName: Database.IDtTabInfo
- uid: Database.ISeqTabInfo
  commentId: T:Database.ISeqTabInfo
  parent: Database
  name: ISeqTabInfo
  nameWithType: ISeqTabInfo
  fullName: Database.ISeqTabInfo
- uid: Database.ICycleSeqInfo
  commentId: T:Database.ICycleSeqInfo
  parent: Database
  name: ICycleSeqInfo
  nameWithType: ICycleSeqInfo
  fullName: Database.ICycleSeqInfo
- uid: Database.AuditTrailInfo
  commentId: T:Database.AuditTrailInfo
  name: AuditTrailInfo
  nameWithType: AuditTrailInfo
  fullName: Database.AuditTrailInfo
- uid: Database.AccessTableInfo
  commentId: T:Database.AccessTableInfo
  name: AccessTableInfo
  nameWithType: AccessTableInfo
  fullName: Database.AccessTableInfo
- uid: Database.RecipeInfo
  commentId: T:Database.RecipeInfo
  name: RecipeInfo
  nameWithType: RecipeInfo
  fullName: Database.RecipeInfo
- uid: Database.RecipeWeightInfo
  commentId: T:Database.RecipeWeightInfo
  parent: Database
  name: RecipeWeightInfo
  nameWithType: RecipeWeightInfo
  fullName: Database.RecipeWeightInfo
- uid: Database.RecipeSpeedMixerInfo
  commentId: T:Database.RecipeSpeedMixerInfo
  parent: Database
  name: RecipeSpeedMixerInfo
  nameWithType: RecipeSpeedMixerInfo
  fullName: Database.RecipeSpeedMixerInfo
- uid: Database.CycleTableInfo
  commentId: T:Database.CycleTableInfo
  parent: Database
  name: CycleTableInfo
  nameWithType: CycleTableInfo
  fullName: Database.CycleTableInfo
- uid: Database.CycleWeightInfo
  commentId: T:Database.CycleWeightInfo
  name: CycleWeightInfo
  nameWithType: CycleWeightInfo
  fullName: Database.CycleWeightInfo
- uid: Database.CycleSpeedMixerInfo
  commentId: T:Database.CycleSpeedMixerInfo
  name: CycleSpeedMixerInfo
  nameWithType: CycleSpeedMixerInfo
  fullName: Database.CycleSpeedMixerInfo
- uid: Database.TempInfo
  commentId: T:Database.TempInfo
  name: TempInfo
  nameWithType: TempInfo
  fullName: Database.TempInfo
- uid: Database.TempResultInfo
  commentId: T:Database.TempResultInfo
  parent: Database
  name: TempResultInfo
  nameWithType: TempResultInfo
  fullName: Database.TempResultInfo
- uid: Database.DailyTestInfo
  commentId: T:Database.DailyTestInfo
  parent: Database
  name: DailyTestInfo
  nameWithType: DailyTestInfo
  fullName: Database.DailyTestInfo
- uid: Database
  commentId: N:Database
  name: Database
  nameWithType: Database
  fullName: Database
