### YamlMime:ManagedReference
items:
- uid: Driver_MODBUS.SpeedMixerSettings
  commentId: T:Driver_MODBUS.SpeedMixerSettings
  id: SpeedMixerSettings
  parent: Driver_MODBUS
  children:
  - Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidClosed
  - Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidOpen
  - Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerError
  - Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerRunning
  - Driver_MODBUS.SpeedMixerSettings.MixerStatusId_ReadyToRun
  - Driver_MODBUS.SpeedMixerSettings.MixerStatusId_RobotAtHome
  - Driver_MODBUS.SpeedMixerSettings.MixerStatusId_SafetyOK
  langs:
  - csharp
  - vb
  name: SpeedMixerSettings
  nameWithType: SpeedMixerSettings
  fullName: Driver_MODBUS.SpeedMixerSettings
  type: Class
  source:
    id: SpeedMixerSettings
    path: C:\Temp\MixingApplication\Driver_MODBUS\SpeedMixerModbus.cs
    startLine: 28
  assemblies:
  - Driver.MODBUS
  namespace: Driver_MODBUS
  summary: "\n\n"
  example: []
  syntax:
    content: public static class SpeedMixerSettings
    content.vb: Public Module SpeedMixerSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_ReadyToRun
  commentId: P:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_ReadyToRun
  id: MixerStatusId_ReadyToRun
  parent: Driver_MODBUS.SpeedMixerSettings
  langs:
  - csharp
  - vb
  name: MixerStatusId_ReadyToRun
  nameWithType: SpeedMixerSettings.MixerStatusId_ReadyToRun
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_ReadyToRun
  type: Property
  source:
    id: MixerStatusId_ReadyToRun
    path: C:\Temp\MixingApplication\Driver_MODBUS\SpeedMixerModbus.cs
    startLine: 30
  assemblies:
  - Driver.MODBUS
  namespace: Driver_MODBUS
  syntax:
    content: public static int MixerStatusId_ReadyToRun { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared ReadOnly Property MixerStatusId_ReadyToRun As Integer
  overload: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_ReadyToRun*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerRunning
  commentId: P:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerRunning
  id: MixerStatusId_MixerRunning
  parent: Driver_MODBUS.SpeedMixerSettings
  langs:
  - csharp
  - vb
  name: MixerStatusId_MixerRunning
  nameWithType: SpeedMixerSettings.MixerStatusId_MixerRunning
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerRunning
  type: Property
  source:
    id: MixerStatusId_MixerRunning
    path: C:\Temp\MixingApplication\Driver_MODBUS\SpeedMixerModbus.cs
    startLine: 31
  assemblies:
  - Driver.MODBUS
  namespace: Driver_MODBUS
  syntax:
    content: public static int MixerStatusId_MixerRunning { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared ReadOnly Property MixerStatusId_MixerRunning As Integer
  overload: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerRunning*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerError
  commentId: P:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerError
  id: MixerStatusId_MixerError
  parent: Driver_MODBUS.SpeedMixerSettings
  langs:
  - csharp
  - vb
  name: MixerStatusId_MixerError
  nameWithType: SpeedMixerSettings.MixerStatusId_MixerError
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerError
  type: Property
  source:
    id: MixerStatusId_MixerError
    path: C:\Temp\MixingApplication\Driver_MODBUS\SpeedMixerModbus.cs
    startLine: 32
  assemblies:
  - Driver.MODBUS
  namespace: Driver_MODBUS
  syntax:
    content: public static int MixerStatusId_MixerError { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared ReadOnly Property MixerStatusId_MixerError As Integer
  overload: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerError*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidOpen
  commentId: P:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidOpen
  id: MixerStatusId_LidOpen
  parent: Driver_MODBUS.SpeedMixerSettings
  langs:
  - csharp
  - vb
  name: MixerStatusId_LidOpen
  nameWithType: SpeedMixerSettings.MixerStatusId_LidOpen
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidOpen
  type: Property
  source:
    id: MixerStatusId_LidOpen
    path: C:\Temp\MixingApplication\Driver_MODBUS\SpeedMixerModbus.cs
    startLine: 33
  assemblies:
  - Driver.MODBUS
  namespace: Driver_MODBUS
  syntax:
    content: public static int MixerStatusId_LidOpen { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared ReadOnly Property MixerStatusId_LidOpen As Integer
  overload: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidOpen*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidClosed
  commentId: P:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidClosed
  id: MixerStatusId_LidClosed
  parent: Driver_MODBUS.SpeedMixerSettings
  langs:
  - csharp
  - vb
  name: MixerStatusId_LidClosed
  nameWithType: SpeedMixerSettings.MixerStatusId_LidClosed
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidClosed
  type: Property
  source:
    id: MixerStatusId_LidClosed
    path: C:\Temp\MixingApplication\Driver_MODBUS\SpeedMixerModbus.cs
    startLine: 34
  assemblies:
  - Driver.MODBUS
  namespace: Driver_MODBUS
  syntax:
    content: public static int MixerStatusId_LidClosed { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared ReadOnly Property MixerStatusId_LidClosed As Integer
  overload: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidClosed*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_SafetyOK
  commentId: P:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_SafetyOK
  id: MixerStatusId_SafetyOK
  parent: Driver_MODBUS.SpeedMixerSettings
  langs:
  - csharp
  - vb
  name: MixerStatusId_SafetyOK
  nameWithType: SpeedMixerSettings.MixerStatusId_SafetyOK
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_SafetyOK
  type: Property
  source:
    id: MixerStatusId_SafetyOK
    path: C:\Temp\MixingApplication\Driver_MODBUS\SpeedMixerModbus.cs
    startLine: 35
  assemblies:
  - Driver.MODBUS
  namespace: Driver_MODBUS
  syntax:
    content: public static int MixerStatusId_SafetyOK { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared ReadOnly Property MixerStatusId_SafetyOK As Integer
  overload: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_SafetyOK*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_RobotAtHome
  commentId: P:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_RobotAtHome
  id: MixerStatusId_RobotAtHome
  parent: Driver_MODBUS.SpeedMixerSettings
  langs:
  - csharp
  - vb
  name: MixerStatusId_RobotAtHome
  nameWithType: SpeedMixerSettings.MixerStatusId_RobotAtHome
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_RobotAtHome
  type: Property
  source:
    id: MixerStatusId_RobotAtHome
    path: C:\Temp\MixingApplication\Driver_MODBUS\SpeedMixerModbus.cs
    startLine: 36
  assemblies:
  - Driver.MODBUS
  namespace: Driver_MODBUS
  syntax:
    content: public static int MixerStatusId_RobotAtHome { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared ReadOnly Property MixerStatusId_RobotAtHome As Integer
  overload: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_RobotAtHome*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Driver_MODBUS
  commentId: N:Driver_MODBUS
  name: Driver_MODBUS
  nameWithType: Driver_MODBUS
  fullName: Driver_MODBUS
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_ReadyToRun*
  commentId: Overload:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_ReadyToRun
  name: MixerStatusId_ReadyToRun
  nameWithType: SpeedMixerSettings.MixerStatusId_ReadyToRun
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_ReadyToRun
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerRunning*
  commentId: Overload:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerRunning
  name: MixerStatusId_MixerRunning
  nameWithType: SpeedMixerSettings.MixerStatusId_MixerRunning
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerRunning
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerError*
  commentId: Overload:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerError
  name: MixerStatusId_MixerError
  nameWithType: SpeedMixerSettings.MixerStatusId_MixerError
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_MixerError
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidOpen*
  commentId: Overload:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidOpen
  name: MixerStatusId_LidOpen
  nameWithType: SpeedMixerSettings.MixerStatusId_LidOpen
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidOpen
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidClosed*
  commentId: Overload:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidClosed
  name: MixerStatusId_LidClosed
  nameWithType: SpeedMixerSettings.MixerStatusId_LidClosed
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_LidClosed
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_SafetyOK*
  commentId: Overload:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_SafetyOK
  name: MixerStatusId_SafetyOK
  nameWithType: SpeedMixerSettings.MixerStatusId_SafetyOK
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_SafetyOK
- uid: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_RobotAtHome*
  commentId: Overload:Driver_MODBUS.SpeedMixerSettings.MixerStatusId_RobotAtHome
  name: MixerStatusId_RobotAtHome
  nameWithType: SpeedMixerSettings.MixerStatusId_RobotAtHome
  fullName: Driver_MODBUS.SpeedMixerSettings.MixerStatusId_RobotAtHome
