//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int scanConnectTimer_Interval {
            get {
                return ((int)(this["scanConnectTimer_Interval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("audit_trail")]
        public string AuditTrail_TableName {
            get {
                return ((string)(this["AuditTrail_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>id</string>
  <string>date_time</string>
  <string>username</string>
  <string>event_type</string>
  <string>description</string>
  <string>value_before</string>
  <string>value_after</string>
  <string>comment</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AuditTrail_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AuditTrail_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe")]
        public string Recipe_TableName {
            get {
                return ((string)(this["Recipe_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>id</string>
  <string>first_seq_type</string>
  <string>first_seq_id</string>
  <string>name</string>
  <string>version</string>
  <string>status</string>
  <string>finalweight_min</string>
  <string>finalweight_max</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Recipe_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Recipe_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AuditTrail_ColN_id {
            get {
                return ((int)(this["AuditTrail_ColN_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AuditTrail_ColN_dateTime {
            get {
                return ((int)(this["AuditTrail_ColN_dateTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AuditTrail_ColN_username {
            get {
                return ((int)(this["AuditTrail_ColN_username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AuditTrail_ColN_eventType {
            get {
                return ((int)(this["AuditTrail_ColN_eventType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int AuditTrail_ColN_description {
            get {
                return ((int)(this["AuditTrail_ColN_description"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AuditTrail_ColN_valueBefore {
            get {
                return ((int)(this["AuditTrail_ColN_valueBefore"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int AuditTrail_ColN_valueAfter {
            get {
                return ((int)(this["AuditTrail_ColN_valueAfter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int AuditTrail_ColN_comment {
            get {
                return ((int)(this["AuditTrail_ColN_comment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Recipe_ColN_id {
            get {
                return ((int)(this["Recipe_ColN_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Recipe_ColN_nextSeqType {
            get {
                return ((int)(this["Recipe_ColN_nextSeqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Recipe_ColN_nextSeqId {
            get {
                return ((int)(this["Recipe_ColN_nextSeqId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Recipe_ColN_recipeName {
            get {
                return ((int)(this["Recipe_ColN_recipeName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Recipe_ColN_version {
            get {
                return ((int)(this["Recipe_ColN_version"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Recipe_ColN_status {
            get {
                return ((int)(this["Recipe_ColN_status"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_weight")]
        public string RecipeWeight_TableName {
            get {
                return ((string)(this["RecipeWeight_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>id</string>
  <string>next_seq_type</string>
  <string>next_seq_id</string>
  <string>name</string>
  <string>is_barcode_used</string>
  <string>barcode</string>
  <string>unit</string>
  <string>decimal_number</string>
  <string>setpoint</string>
  <string>criteria</string>
  <string>is_solvent</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RecipeWeight_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecipeWeight_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RecipeWeight_ColN_id {
            get {
                return ((int)(this["RecipeWeight_ColN_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RecipeWeight_ColN_nextSeqType {
            get {
                return ((int)(this["RecipeWeight_ColN_nextSeqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RecipeWeight_ColN_nextSeqId {
            get {
                return ((int)(this["RecipeWeight_ColN_nextSeqId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RecipeWeight_ColN_seqName {
            get {
                return ((int)(this["RecipeWeight_ColN_seqName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int RecipeWeight_ColN_isBarcodeUsed {
            get {
                return ((int)(this["RecipeWeight_ColN_isBarcodeUsed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RecipeWeight_ColN_barcode {
            get {
                return ((int)(this["RecipeWeight_ColN_barcode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int RecipeWeight_ColN_unit {
            get {
                return ((int)(this["RecipeWeight_ColN_unit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int RecipeWeight_ColN_decimalNumber {
            get {
                return ((int)(this["RecipeWeight_ColN_decimalNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int RecipeWeight_ColN_setpoint {
            get {
                return ((int)(this["RecipeWeight_ColN_setpoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int RecipeWeight_ColN_criteria {
            get {
                return ((int)(this["RecipeWeight_ColN_criteria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RecipeWeight_ColN_isSolvent {
            get {
                return ((int)(this["RecipeWeight_ColN_isSolvent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipe_speedmixer")]
        public string RecipeSpeedMixer_TableName {
            get {
                return ((string)(this["RecipeSpeedMixer_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>id</string>\r\n  <string>next_seq_type</string>\r\n  <string>next_seq_id</stri" +
            "ng>\r\n  <string>name</string>\r\n  <string>acceleration</string>\r\n  <string>deceler" +
            "ation</string>\r\n  <string>vaccum_control</string>\r\n  <string>is_ventgas_air</str" +
            "ing>\r\n  <string>monitor_type</string>\r\n  <string>pressure_unit</string>\r\n  <stri" +
            "ng>scurve</string>\r\n  <string>coldtrap</string>\r\n  <string>speed00</string>\r\n  <" +
            "string>time00</string>\r\n  <string>pressure00</string>\r\n  <string>speed01</string" +
            ">\r\n  <string>time01</string>\r\n  <string>pressure01</string>\r\n  <string>speed02</" +
            "string>\r\n  <string>time02</string>\r\n  <string>pressure02</string>\r\n  <string>spe" +
            "ed03</string>\r\n  <string>time03</string>\r\n  <string>pressure03</string>\r\n  <stri" +
            "ng>speed04</string>\r\n  <string>time04</string>\r\n  <string>pressure04</string>\r\n " +
            " <string>speed05</string>\r\n  <string>time05</string>\r\n  <string>pressure05</stri" +
            "ng>\r\n  <string>speed06</string>\r\n  <string>time06</string>\r\n  <string>pressure06" +
            "</string>\r\n  <string>speed07</string>\r\n  <string>time07</string>\r\n  <string>pres" +
            "sure07</string>\r\n  <string>speed08</string>\r\n  <string>time08</string>\r\n  <strin" +
            "g>pressure08</string>\r\n  <string>speed09</string>\r\n  <string>time09</string>\r\n  " +
            "<string>pressure09</string>\r\n  <string>speed_min</string>\r\n  <string>speed_max</" +
            "string>\r\n  <string>pressure_min</string>\r\n  <string>pressure_max</string>\r\n</Arr" +
            "ayOfString>")]
        public global::System.Collections.Specialized.StringCollection RecipeSpeedMixer_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecipeSpeedMixer_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RecipeSpeedMixer_ColN_id {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RecipeSpeedMixer_ColN_nextSeqType {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_nextSeqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RecipeSpeedMixer_ColN_nextSeqId {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_nextSeqId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RecipeSpeedMixer_ColN_seqName {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_seqName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int RecipeSpeedMixer_ColN_acceleration {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_acceleration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RecipeSpeedMixer_ColN_deceleration {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_deceleration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int RecipeSpeedMixer_ColN_vaccumControl {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_vaccumControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int RecipeSpeedMixer_ColN_isVentgasAir {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_isVentgasAir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int RecipeSpeedMixer_ColN_monitorType {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_monitorType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int RecipeSpeedMixer_ColN_pressureUnit {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_pressureUnit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RecipeSpeedMixer_ColN_scurve {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_scurve"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int RecipeSpeedMixer_ColN_coldtrap {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_coldtrap"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int RecipeSpeedMixer_ColN_speed00 {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_speed00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int RecipeSpeedMixer_ColN_time00 {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_time00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int RecipeSpeedMixer_ColN_pressure00 {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_pressure00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42")]
        public int RecipeSpeedMixer_ColN_speedMin {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_speedMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43")]
        public int RecipeSpeedMixer_ColN_speedMax {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_speedMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44")]
        public int RecipeSpeedMixer_ColN_pressureMin {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_pressureMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int RecipeSpeedMixer_ColN_pressureMax {
            get {
                return ((int)(this["RecipeSpeedMixer_ColN_pressureMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RecipeWeight_seqType {
            get {
                return ((int)(this["RecipeWeight_seqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RecipeSpeedMixer_seqType {
            get {
                return ((int)(this["RecipeSpeedMixer_seqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cycle")]
        public string Cycle_TableName {
            get {
                return ((string)(this["Cycle_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>id</string>
  <string>next_seq_type</string>
  <string>next_seq_id</string>
  <string>job_number</string>
  <string>batch_number</string>
  <string>quantity_value</string>
  <string>quantity_unit</string>
  <string>item_number</string>
  <string>recipe_name</string>
  <string>recipe_version</string>
  <string>equipment_name</string>
  <string>date_time_start_cycle</string>
  <string>date_time_end_cycle</string>
  <string>username</string>
  <string>first_alarm_id</string>
  <string>last_alarm_id</string>
  <string>comment</string>
  <string>is_it_a_test</string>
  <string>bowl_weight</string>
  <string>last_weight_th</string>
  <string>last_weight_eff</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Cycle_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Cycle_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Cycle_ColN_id {
            get {
                return ((int)(this["Cycle_ColN_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Cycle_ColN_nextSeqType {
            get {
                return ((int)(this["Cycle_ColN_nextSeqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Cycle_ColN_nextSeqId {
            get {
                return ((int)(this["Cycle_ColN_nextSeqId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Cycle_ColN_jobNumber {
            get {
                return ((int)(this["Cycle_ColN_jobNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Cycle_ColN_batchNumber {
            get {
                return ((int)(this["Cycle_ColN_batchNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Cycle_ColN_quantityValue {
            get {
                return ((int)(this["Cycle_ColN_quantityValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Cycle_ColN_quantityUnit {
            get {
                return ((int)(this["Cycle_ColN_quantityUnit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Cycle_ColN_itemNumber {
            get {
                return ((int)(this["Cycle_ColN_itemNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int Cycle_ColN_recipeName {
            get {
                return ((int)(this["Cycle_ColN_recipeName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int Cycle_ColN_recipeVersion {
            get {
                return ((int)(this["Cycle_ColN_recipeVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Cycle_ColN_equipmentName {
            get {
                return ((int)(this["Cycle_ColN_equipmentName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int Cycle_ColN_dateTimeStartCycle {
            get {
                return ((int)(this["Cycle_ColN_dateTimeStartCycle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Cycle_ColN_dateTimeEndCycle {
            get {
                return ((int)(this["Cycle_ColN_dateTimeEndCycle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int Cycle_ColN_username {
            get {
                return ((int)(this["Cycle_ColN_username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int Cycle_ColN_firstAlarmId {
            get {
                return ((int)(this["Cycle_ColN_firstAlarmId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Cycle_ColN_lastAlarmId {
            get {
                return ((int)(this["Cycle_ColN_lastAlarmId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int Cycle_ColN_comment {
            get {
                return ((int)(this["Cycle_ColN_comment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int Cycle_ColN_isItATest {
            get {
                return ((int)(this["Cycle_ColN_isItATest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cycle_weight")]
        public string CycleWeight_TableName {
            get {
                return ((string)(this["CycleWeight_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>id</string>
  <string>next_seq_type</string>
  <string>next_seq_id</string>
  <string>product</string>
  <string>was_weight_manual</string>
  <string>date_time</string>
  <string>actual_value</string>
  <string>setpoint</string>
  <string>minimum</string>
  <string>maximum</string>
  <string>unit</string>
  <string>decimal_number</string>
  <string>is_solvent</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CycleWeight_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CycleWeight_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CycleWeight_ColN_id {
            get {
                return ((int)(this["CycleWeight_ColN_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CycleWeight_ColN_nextSeqType {
            get {
                return ((int)(this["CycleWeight_ColN_nextSeqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CycleWeight_ColN_nextSeqId {
            get {
                return ((int)(this["CycleWeight_ColN_nextSeqId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CycleWeight_ColN_product {
            get {
                return ((int)(this["CycleWeight_ColN_product"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CycleWeight_ColN_wasWeightManual {
            get {
                return ((int)(this["CycleWeight_ColN_wasWeightManual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CycleWeight_ColN_dateTime {
            get {
                return ((int)(this["CycleWeight_ColN_dateTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int CycleWeight_ColN_actualValue {
            get {
                return ((int)(this["CycleWeight_ColN_actualValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int CycleWeight_ColN_setpoint {
            get {
                return ((int)(this["CycleWeight_ColN_setpoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int CycleWeight_ColN_min {
            get {
                return ((int)(this["CycleWeight_ColN_min"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int CycleWeight_ColN_max {
            get {
                return ((int)(this["CycleWeight_ColN_max"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CycleWeight_ColN_unit {
            get {
                return ((int)(this["CycleWeight_ColN_unit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int CycleWeight_ColN_decimalNumber {
            get {
                return ((int)(this["CycleWeight_ColN_decimalNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CycleWeight_seqType {
            get {
                return ((int)(this["CycleWeight_seqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CycleSpeedMixer_seqType {
            get {
                return ((int)(this["CycleSpeedMixer_seqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cycle_speedmixer")]
        public string CycleSpeedMixer_TableName {
            get {
                return ((string)(this["CycleSpeedMixer_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>id</string>
  <string>next_seq_type</string>
  <string>next_seq_id</string>
  <string>name</string>
  <string>date_time_start</string>
  <string>date_time_end</string>
  <string>time_mix_th</string>
  <string>time_mix_eff</string>
  <string>pressure_unit</string>
  <string>speed_min</string>
  <string>speed_max</string>
  <string>pressure_min</string>
  <string>pressure_max</string>
  <string>speed_mean</string>
  <string>pressure_mean</string>
  <string>speed_std</string>
  <string>pressure_std</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CycleSpeedMixer_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CycleSpeedMixer_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CycleSpeedMixer_ColN_id {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CycleSpeedMixer_ColN_nextSeqType {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_nextSeqType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CycleSpeedMixer_ColN_nextSeqId {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_nextSeqId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CycleSpeedMixer_ColN_dateTimeStart {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_dateTimeStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CycleSpeedMixer_ColN_dateTimeEnd {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_dateTimeEnd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int CycleSpeedMixer_ColN_timeMixTh {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_timeMixTh"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int CycleSpeedMixer_ColN_timeMixEff {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_timeMixEff"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int CycleSpeedMixer_ColN_pressureUnit {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_pressureUnit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int CycleSpeedMixer_ColN_speedMin {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_speedMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CycleSpeedMixer_ColN_speedMax {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_speedMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int CycleSpeedMixer_ColN_pressureMin {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_pressureMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int CycleSpeedMixer_ColN_pressureMax {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_pressureMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int CycleSpeedMixer_ColN_speedMean {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_speedMean"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int CycleSpeedMixer_ColN_pressureMean {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_pressureMean"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int CycleSpeedMixer_ColN_speedStd {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_speedStd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int CycleSpeedMixer_ColN_pressureStd {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_pressureStd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tentative de reconnexion. Statut: ")]
        public string Info01 {
            get {
                return ((string)(this["Info01"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Connection à la base de données échouée")]
        public string Error_connectToDbFailed {
            get {
                return ((string)(this["Error_connectToDbFailed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Création de la commande incorrecte")]
        public string Error02 {
            get {
                return ((string)(this["Error02"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Non, ce n\'est pas vrai. Non non NON !")]
        public string Error03 {
            get {
                return ((string)(this["Error03"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le reader n\'est pas disponible")]
        public string Error04 {
            get {
                return ((string)(this["Error04"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La commande renvoie plus d\'une ligne")]
        public string Error05 {
            get {
                return ((string)(this["Error05"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le nombre de colonnes est différent du nombre de valeurs")]
        public string Error06 {
            get {
                return ((string)(this["Error06"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La variable tableInfo est null")]
        public string Error07 {
            get {
                return ((string)(this["Error07"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Il n\'y a pas de colonne")]
        public string Error08 {
            get {
                return ((string)(this["Error08"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aucune valeur n\'a été renseignée")]
        public string Error09 {
            get {
                return ((string)(this["Error09"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Il y a plus d\'index que de colonnes")]
        public string Error10 {
            get {
                return ((string)(this["Error10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C\'est pas bon ça, regarde le log")]
        public string Error11 {
            get {
                return ((string)(this["Error11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La classe n\'est pas initialisée")]
        public string Error12 {
            get {
                return ((string)(this["Error12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temp")]
        public string Temp_TableName {
            get {
                return ((string)(this["Temp_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Numéro de ligne manquant")]
        public string Error13 {
            get {
                return ((string)(this["Error13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nombre de colonnes incorrect")]
        public string Error14 {
            get {
                return ((string)(this["Error14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le tableau contient au moins 2 lignes avec le même id")]
        public string Error15 {
            get {
                return ((string)(this["Error15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Torr")]
        public string RecipeSpeedMixer_PressureUnit_Torr {
            get {
                return ((string)(this["RecipeSpeedMixer_PressureUnit_Torr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mBar")]
        public string RecipeSpeedMixer_PressureUnit_mBar {
            get {
                return ((string)(this["RecipeSpeedMixer_PressureUnit_mBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inHg")]
        public string RecipeSpeedMixer_PressureUnit_inHg {
            get {
                return ((string)(this["RecipeSpeedMixer_PressureUnit_inHg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PSIA")]
        public string RecipeSpeedMixer_PressureUnit_PSIA {
            get {
                return ((string)(this["RecipeSpeedMixer_PressureUnit_PSIA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string General_TrueValue_Read {
            get {
                return ((string)(this["General_TrueValue_Read"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string General_FalseValue_Read {
            get {
                return ((string)(this["General_FalseValue_Read"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>id</string>
  <string>role</string>
  <string>cycle_start</string>
  <string>recipe_update</string>
  <string>backup</string>
  <string>parameters</string>
  <string>daily_test</string>
  <string>application_stop</string>
  <string>ack_alarm</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AccessTable_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AccessTable_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("access_table")]
        public string AccessTable_TableName {
            get {
                return ((string)(this["AccessTable_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AccessTable_ColN_id {
            get {
                return ((int)(this["AccessTable_ColN_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AccessTable_ColN_role {
            get {
                return ((int)(this["AccessTable_ColN_role"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AccessTable_ColN_cycleStart {
            get {
                return ((int)(this["AccessTable_ColN_cycleStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AccessTable_ColN_recipeCreate {
            get {
                return ((int)(this["AccessTable_ColN_recipeCreate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int AccessTable_ColN_applicationStop {
            get {
                return ((int)(this["AccessTable_ColN_applicationStop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("opérateur")]
        public string AccessTable_Role_operator {
            get {
                return ((string)(this["AccessTable_Role_operator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("superviseur")]
        public string AccessTable_Role_supervisor {
            get {
                return ((string)(this["AccessTable_Role_supervisor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("administrateur")]
        public string AccessTable_Role_administrator {
            get {
                return ((string)(this["AccessTable_Role_administrator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("invité")]
        public string AccessTable_Role_none {
            get {
                return ((string)(this["AccessTable_Role_none"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>Produit</string>
  <string>0</string>
  <string>Date et heure de pesée</string>
  <string>Valeur pesée</string>
  <string>Valeur nominal</string>
  <string>Minimum</string>
  <string>Maximum</string>
  <string>0</string>
  <string>0</string>
  <string>Solvant</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CycleWeight_ColDesc {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CycleWeight_ColDesc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CycleSpeedMixer_ColN_mixName {
            get {
                return ((int)(this["CycleSpeedMixer_ColN_mixName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>Nom du mélange</string>
  <string>Début séquence</string>
  <string>Fin séquence</string>
  <string>Durée Mix théorique</string>
  <string>Durée Mix effective</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CycleSpeedMixer_ColDesc {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CycleSpeedMixer_ColDesc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arguments manquants")]
        public string Error16 {
            get {
                return ((string)(this["Error16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La commande ne renvoie rien")]
        public string Error17 {
            get {
                return ((string)(this["Error17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>speed</string>\r\n  <string>pressure</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Temp_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Temp_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Temp_ColN_speed {
            get {
                return ((int)(this["Temp_ColN_speed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Temp_ColN_pressure {
            get {
                return ((int)(this["Temp_ColN_pressure"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int TempResult_ColN {
            get {
                return ((int)(this["TempResult_ColN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TempResult_ColN_speedMean {
            get {
                return ((int)(this["TempResult_ColN_speedMean"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TempResult_ColN_pressureMean {
            get {
                return ((int)(this["TempResult_ColN_pressureMean"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TempResult_ColN_speedStd {
            get {
                return ((int)(this["TempResult_ColN_speedStd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TempResult_ColN_pressureStd {
            get {
                return ((int)(this["TempResult_ColN_pressureStd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string General_TrueValue_Write {
            get {
                return ((string)(this["General_TrueValue_Write"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string General_FalseValue_Write {
            get {
                return ((string)(this["General_FalseValue_Write"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ID</string>
  <string>Date et heure</string>
  <string>Utilisateur</string>
  <string>Type d'évènement</string>
  <string>Description</string>
  <string>Valeur avant</string>
  <string>Valeur après</string>
  <string>Commentaire</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AuditTrail_ColDesc {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AuditTrail_ColDesc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\MariaDB 10.9\\bin")]
        public string DBAppFolder {
            get {
                return ((string)(this["DBAppFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>recette</string>
  <string>version</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Recipe_ColDesc {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Recipe_ColDesc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int MaxNumbRows {
            get {
                return ((int)(this["MaxNumbRows"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nombre de lignes demandées incorrect")]
        public string Error_NumbRowsIncorrect {
            get {
                return ((string)(this["Error_NumbRowsIncorrect"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Je n\'ai pas réussi à tout lire, il y a en trop")]
        public string Error_IDidntReadItAll {
            get {
                return ((string)(this["Error_IDidntReadItAll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Date et temps avant ou après incorrect")]
        public string Error_ReadAudit_ArgIncorrect {
            get {
                return ((string)(this["Error_ReadAudit_ArgIncorrect"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mg/g")]
        public string RecipeWeight_mgG_Unit {
            get {
                return ((string)(this["RecipeWeight_mgG_Unit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("g/g")]
        public string RecipeWeight_gG_Unit {
            get {
                return ((string)(this["RecipeWeight_gG_Unit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type de la recette utilisé incorrect")]
        public string ICycleSeqInfo_Error_RecipeIncorrect {
            get {
                return ((string)(this["ICycleSeqInfo_Error_RecipeIncorrect"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Elle vient d\'ici l\'erreur")]
        public string Error_FromHere {
            get {
                return ((string)(this["Error_FromHere"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unités de pesée incorrectes")]
        public string ICycleSeqInfo_Error_convRatioIncorrect {
            get {
                return ((string)(this["ICycleSeqInfo_Error_convRatioIncorrect"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int QueueEmptyTimer_Interval {
            get {
                return ((int)(this["QueueEmptyTimer_Interval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int IsQueueAvailableTimer_Interval {
            get {
                return ((int)(this["IsQueueAvailableTimer_Interval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int QueueEmptyCount_Max {
            get {
                return ((int)(this["QueueEmptyCount_Max"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TaskDeQueue_Wait {
            get {
                return ((int)(this["TaskDeQueue_Wait"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Disconnect_WaitTime {
            get {
                return ((int)(this["Disconnect_WaitTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Recipe_ColN_FinalWeightMin {
            get {
                return ((int)(this["Recipe_ColN_FinalWeightMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Recipe_ColN_FinalWeightMax {
            get {
                return ((int)(this["Recipe_ColN_FinalWeightMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int Cycle_ColN_bowlWeight {
            get {
                return ((int)(this["Cycle_ColN_bowlWeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int CycleWeight_ColN_isSolvent {
            get {
                return ((int)(this["CycleWeight_ColN_isSolvent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int Cycle_ColN_lastWeightTh {
            get {
                return ((int)(this["Cycle_ColN_lastWeightTh"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Cycle_ColN_lastWeightEff {
            get {
                return ((int)(this["Cycle_ColN_lastWeightEff"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>id</string>
  <string>username</string>
  <string>date_time</string>
  <string>equipment_name</string>
  <string>setpoint1</string>
  <string>setpoint2</string>
  <string>setpoint3</string>
  <string>setpoint4</string>
  <string>measure1</string>
  <string>measure2</string>
  <string>measure3</string>
  <string>measure4</string>
  <string>status</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Sample_ColIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Sample_ColIds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>0</string>
  <string>Nom d'utilisateur</string>
  <string>Date et heure de l'étalonnage</string>
  <string>Nom de l'équipement</string>
  <string>Poids étalon 1</string>
  <string>Poids étalon 2</string>
  <string>Poids étalon 3</string>
  <string>Poids étalon 4</string>
  <string>Masse mesurée</string>
  <string>Masse mesurée</string>
  <string>Masse mesurée</string>
  <string>Masse mesurée</string>
  <string>Statut</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Sample_ColDesc {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Sample_ColDesc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sampling")]
        public string Sample_TableName {
            get {
                return ((string)(this["Sample_TableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Sample_ColN_id {
            get {
                return ((int)(this["Sample_ColN_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Sample_ColN_dateTime {
            get {
                return ((int)(this["Sample_ColN_dateTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Sample_ColN_setpoint1 {
            get {
                return ((int)(this["Sample_ColN_setpoint1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Sample_ColN_setpoint2 {
            get {
                return ((int)(this["Sample_ColN_setpoint2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Sample_ColN_setpoint3 {
            get {
                return ((int)(this["Sample_ColN_setpoint3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Sample_ColN_setpoint4 {
            get {
                return ((int)(this["Sample_ColN_setpoint4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int Sample_ColN_measure1 {
            get {
                return ((int)(this["Sample_ColN_measure1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int Sample_ColN_measure2 {
            get {
                return ((int)(this["Sample_ColN_measure2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Sample_ColN_measure3 {
            get {
                return ((int)(this["Sample_ColN_measure3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int Sample_ColN_measure4 {
            get {
                return ((int)(this["Sample_ColN_measure4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Sample_ColN_status {
            get {
                return ((int)(this["Sample_ColN_status"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Sample_ColN_username {
            get {
                return ((int)(this["Sample_ColN_username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy-MM-dd HH:mm:ss")]
        public string Timestamp_Format {
            get {
                return ((string)(this["Timestamp_Format"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Sample_ColN_equipmentName {
            get {
                return ((int)(this["Sample_ColN_equipmentName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int AccessTable_ColN_Backup {
            get {
                return ((int)(this["AccessTable_ColN_Backup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AccessTable_ColN_Parameters {
            get {
                return ((int)(this["AccessTable_ColN_Parameters"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int AccessTable_ColN_DailyTest {
            get {
                return ((int)(this["AccessTable_ColN_DailyTest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int AccessTable_ColN_AckAlarm {
            get {
                return ((int)(this["AccessTable_ColN_AckAlarm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ConnectionInfo xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <Server>localhost</Server>
  <UserID>root</UserID>
  <Password>Integra2022/</Password>
  <Db>db1</Db>
</ConnectionInfo>")]
        public global::Database.ConnectionInfo ConnectionInfo {
            get {
                return ((global::Database.ConnectionInfo)(this["ConnectionInfo"]));
            }
        }
    }
}
